apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-backend-deployment
  labels:
    app: capstone-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-backend
  strategy:
    rollingUpdate:
      maxSurge: 200%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-backend
    spec:
      serviceAccountName: backend-team-sa
      containers:
      - image: 085519708244.dkr.ecr.us-east-2.amazonaws.com/backend_service:v0.1.3
        imagePullPolicy: Always
        name: capstone-backend
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development