apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-backend-test
  labels:
    app: capstone-backend-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-backend-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-backend-test
    spec:
      containers:
      - image: 085519708244.dkr.ecr.us-east-2.amazonaws.com/backend_service:v0.1.0
        imagePullPolicy: Always
        name: capstone-backend-test
        ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: applicationUrl
            value: "http://+:8080;https://+:8081"
