apiVersion: v1
kind: Service
metadata:
  name: capstone-backend-service
  namespace: backend
  # annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-type: "alb"
  #     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: capstone-backend
  #type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 7070
      targetPort: 8080