apiVersion: v1
kind: Service
metadata:
  name: capstone-frontend-service
  namespace: frontend
  #service.beta.kubernetes.io/aws-load-balancer-name: k8s-default-capstone-b08b3d1a10
spec:
  selector:
    app: capstone-frontend
  
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer